// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Activate(arg1) {
  return window['go']['api']['App']['Activate'](arg1);
}

export function CreateEnv(arg1) {
  return window['go']['api']['App']['CreateEnv'](arg1);
}

export function Deactivate() {
  return window['go']['api']['App']['Deactivate']();
}

export function DisableSkill(arg1, arg2) {
  return window['go']['api']['App']['DisableSkill'](arg1, arg2);
}

export function EnableSkill(arg1, arg2) {
  return window['go']['api']['App']['EnableSkill'](arg1, arg2);
}

export function GetAgentSkills(arg1) {
  return window['go']['api']['App']['GetAgentSkills'](arg1);
}

export function GetAgents() {
  return window['go']['api']['App']['GetAgents']();
}

export function GetEnvs() {
  return window['go']['api']['App']['GetEnvs']();
}

export function GetSkills() {
  return window['go']['api']['App']['GetSkills']();
}

export function GetStatus() {
  return window['go']['api']['App']['GetStatus']();
}

export function ReadSkillContent(arg1, arg2) {
  return window['go']['api']['App']['ReadSkillContent'](arg1, arg2);
}

export function ReadStoreSkillContent(arg1) {
  return window['go']['api']['App']['ReadStoreSkillContent'](arg1);
}

export function RemoveEnv(arg1) {
  return window['go']['api']['App']['RemoveEnv'](arg1);
}

export function RemoveSkill(arg1) {
  return window['go']['api']['App']['RemoveSkill'](arg1);
}

export function ScanAgents() {
  return window['go']['api']['App']['ScanAgents']();
}

export function WriteSkillContent(arg1, arg2, arg3) {
  return window['go']['api']['App']['WriteSkillContent'](arg1, arg2, arg3);
}
