// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {model} from '../models';

export function Activate(arg1:string):Promise<api.OperationResult>;

export function CreateEnv(arg1:string):Promise<api.OperationResult>;

export function Deactivate():Promise<api.OperationResult>;

export function DisableSkill(arg1:string,arg2:string):Promise<api.OperationResult>;

export function EnableSkill(arg1:string,arg2:string):Promise<api.OperationResult>;

export function GetAgentSkills(arg1:string):Promise<Array<model.SkillRef>>;

export function GetAgents():Promise<Array<api.AgentInfo>>;

export function GetEnvs():Promise<Array<api.EnvInfo>>;

export function GetSkills():Promise<Array<api.SkillInfo>>;

export function GetStatus():Promise<api.StatusResponse>;

export function RemoveEnv(arg1:string):Promise<api.OperationResult>;

export function RemoveSkill(arg1:string):Promise<api.OperationResult>;

export function ScanAgents():Promise<api.OperationResult>;
